### ISSUE TITLE
Referral Forms

### ISSUE THREAD

**Issue by MarkNdiema** [andrew-klassen/hope_matters#1]
Referral Form on History text box not retrieving information from the database.

**Comment by andrew-klassen** [comment]
I think I know what you are referring too. I found that when you create a referral form and make a change to it, the history textbox on the form loses its value. 

This is because the name html attribute (name='history') on the history textbox located in change_referral_form.php, is missing. Since it is missing, the history variable in change_referral_form.php receives a blank value from the POST method and submits an empty string into the database. 

Thank you for catching this. I will fix with an official update as soon as possible.

**Comment by MarkNdiema** [comment]
Thanks.
There are more labs to be added in the next update
I'll email you the document.

**Comment by andrew-klassen** [comment]
I pushed out the patch. Please update and verify that it works as soon as possible because this bug results in patient data loss.

**Comment by MarkNdiema** [comment]
Fixed it
Its working..
Thanks

**Comment by MarkNdiema** [comment]
Hi Andrew,

Hope this finds you well been long since we last communicated.
I just wanted to notify you that since Ill be free this month I'll be
adding more labs that were to add on the lab form.
Attached find the labs categorization and more labs that are to be added.

I Just wanted to give you  a heads up before you notice some activities at
the code respiratory: GitHub.


And before I forget can you help me install the spark instant massage via
team viewer  software sometime around this week.
Say Friday/

It gave me a run for my time.

Thanks


Regards


Mark Ndiema
Eldoret, Kenya
